a = float(input("Enter A value: "))
b = float(input("Enter B value: "))
print("Addition of A and B is: ", a+b)
print("Subraction of A and B is: ", a-b)
print("Multiplication of A and B is: ", a*b)
print("Division of A and B is: ", a/b)
